services:
  gateway:
    image: nginx:1-alpine
    ports:
      - 8000:80
    volumes:
      - ./frontend/nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    environment:
      NODE_OPTIONS: '--max-old-space-size=4096'
      DATABASE_URL: postgresql://postgres:secret@host.docker.internal:5432/postgres?schema=public
    depends_on:
      - backend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app/
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: